### ISSUE TITLE
This code works fast

### ISSUE THREAD

**Issue by glanzkaiser** [AugustoCL/gauss_jordan_elimination#1]
I try this and it is faster than the usual `A \ b` 

![Capture d’écran_2022-07-24_20-26-47](https://user-images.githubusercontent.com/72222484/180649162-dff3c2d6-e024-41af-98c5-4617e69d880e.png)

Can you create the code like this for finding determinant with Cramer's rule?

**Comment by AugustoCL** [comment]
Thanks for your words.

But unfortunely, you are misunderstood some important concepts of the Julia Language, like the pre-compilation time because of the Just-In-Time (JIT) compilation paradigm (I really suggest you read about it, it's the main reason that Julia it's so fast). 
If you look at your printscreen, 99% of the 5.77 seconds it was consumed by the compilation time because you just use the macro @time, instead of use the @btime macro from BenchmarkTools.jl package. 

Also, since my code has an educational purpose, I didn't dive so deep about the performance of my code. So if you compare correctly the performance, you will see that the `\` function has a better performance, and has less alocation (because my function return the full matrix and the `\` return just the vector result). 

![image](https://user-images.githubusercontent.com/44294500/180775348-0a351044-5630-4ed7-8fd8-d53a668167d9.png)
